[tool.poetry]
name = "wfdb-python"
version = "3.4.1"
description = "The WFDB Python Package"
authors = ["The Laboratory for Computational Physiology <support@physionet.org>"]
license = "MIT"

[tool.poetry.dependencies]
python = ">=3.8,<3.11"
numpy = "~1.22.3"
pandas = "~1.4.2"
requests = "~2.27.1"
scipy = {version = "~1.7.0", optional = true}
matplotlib = {version = "~3.5.1", optional = true}

[tool.poetry.extras]
plot = ["matplotlib"]
processing = ["scipy"]

[tool.poetry.dev-dependencies]
nose = "~1.3.7"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
