[tool.poetry]
name = "wfdb"
version = "4.0.0a0"
description = "The WFDB Python package: tools for reading, writing, and processing physiologic signals and annotations."
authors = ["The Laboratory for Computational Physiology <contact@physionet.org>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.7"
numpy = "^1.10.1"
scipy = "^1.0.0"
pandas = "^1.0.0"
matplotlib = "^3.3.4"
requests = "^2.8.1"

[tool.poetry.dev-dependencies]
Sphinx = "^4.5.0"
pytest = "^7.1.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
